version: "3.0"

services:

  api:
    build:
      context: ./services/publisher
    image: conduit
    env_file: docker-compose.env
    links:
      - amqp
    depends_on:
      - amqp
    labels:
      - "traefik.enable=true"   
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  consumer:
    build:
      context: ./services/consumer
    image: conduit
    env_file: docker-compose.env
    links:
      - amqp
    depends_on:
      - amqp

  publisher:
    build:
      context: ./services/publisher
    image: conduit
    env_file: docker-compose.env
    links:
      - amqp
    depends_on:
      - amqp


  amqp:
    image: rabbitmq

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "8080:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
